name: Tests

on:
  pull_request:

jobs:
  bats-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install bats-core

      - name: Make scripts executable
        run: |
          chmod +x git-archive
          chmod +x archive.sh
          chmod +x extract.sh

      - name: Run Bats tests
        run: |
          bats tests/
